### ISSUE TITLE
Questions about the query templates

### ISSUE THREAD

**Issue by kaihuchen** [karthikncode/DeepRL-InformationExtraction#2]
@karthikncode 
In the paper it was mentioned: *The queries are based on automatically generated templates, created using the title of an article along with words most likely to co-occur with each entity type in the training data.*  I have a couple of questions regarding these templates: 

1. Where in the code or data files that such templates are generated or located? I have scanned through the files and was unable to find them.
2. Wonder what's your opinion about using Word2Vec to help with creating such templates? My thinking here is that since Word2Vec has the ability to discover structured relationship in the training text corpus, so perhaps the query templates created with it might be more relevant and effective for querying.

Thanks!

**Comment by karthikncode** [comment]
1. Take a look at [ngrams.py](https://github.com/karthikncode/DeepRL-InformationExtraction/blob/master/code/ngrams.py).
2. That's an interesting thought. I guess you could use the learnt representations to find similar words and expand the query by adding in more/different context words? However, the vectors for the named entities are likely to be very noisy, so not sure if one could use this to get good context words directly from the tagged words.

Hope that helps!
